server.port=8080
spring.datasource.url=jdbc:h2:mem:schachdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

admin.username=${ADMIN_USERNAME:admin}
admin.password-hash=${ADMIN_PASSWORD_HASH:$2a$10$Dw/RFPvfvi7EFBSOvg8H3.eSoHBLdayaLKsGb.GeSQCk2iDYZmH8K}
jwt.secret=${JWT_SECRET:LjOkrakBf06zqQJy7MJyvu3K5TkZPbjYMsskUDIBWsZxQQAjjXlAPw/GLrVIiOUR}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}