spring.application.name=Schachdatenverwaltung
spring.h2.console.enabled=true

# Der Pfad, unter dem die Konsole erreichbar ist (Standard: /h2-console)
spring.h2.console.path=/h2-console

# Damit die Datenbank-URL bei jedem Start gleich bleibt (WICHTIG!)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=