spring.application.name=schachdatenverwaltung

spring.datasource.url=jdbc:postgresql://192.168.2.103:5432/schachdatenverwaltung
spring.datasource.username=schachuser
spring.datasource.password=geheim

spring.jpa.hibernate.ddl-auto=update