name: Deploy Schach API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Projekt auschecken
        uses: actions/checkout@v4

      - name: Java 25 einrichten
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Maven Wrapper ausführbar machen
        run: chmod +x mvnw

      - name: Tests und SonarQube Analyse
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw clean verify sonar:sonar \
            -Dsonar.projectKey=fenzeldino_Schachdatenverwaltung \
            -Dsonar.organization=fenzeldino \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}



      - name: Tests ausführen und JAR bauen
        run: ./mvnw clean package

      - name: Docker-Image bauen
        run: docker build -t schach-api:latest .

      - name: Container neu starten
        run: |
          cd /opt/schach-api
          docker compose down
          docker compose up -d --force-recreate

      - name: Containerstatus anzeigen
        run: docker ps --filter "name=schach-api"